### ISSUE TITLE
improve page 

### ISSUE THREAD

**Issue by michael-spengler** [michael-spengler/fairness#2]
to improve the page at https://cultdao-ecosystem.eth.limo/ the following approaches might be followed:   

1. add a decentralized backend (smart-contract based or IPFS based or ?)   
2. consider adding the audio (autoplay) - inspired by the cultdao.io manifest     
3. remove "from ..." in the quote to be posted - to open the system to anyone who wants to donate CULT to newcomers - including smart contracts which might be programmed for this purpose

**Comment by michael-spengler** [comment]
### Regarding Point Number 1
The newcomers (for which https://cultdao-ecosystem.eth.limo/ shall serve) might not have Ether in their browserwallet yet. This is the main reason why I hesitate to implement 1.
--> ... so it looks like going for a centralized backend is reasonable in this context. --> exploring options to use https://certbot.eff.org/ in combination with a https://eth.limo/ based

**Comment by michael-spengler** [comment]
> ### Regarding Point Number 1
> The newcomers (for which https://cultdao-ecosystem.eth.limo/ shall serve) might not have Ether in their browserwallet yet. This is the main reason why I hesitate to implement 1. --> ... so it looks like going for a centralized backend is reasonable in this context. --> exploring options to use https://certbot.eff.org/ in combination with an ens.domains & https://eth.limo/ based page provisioning.

I need to make API calls from https://cultdao-ecosystem.eth.limo/ to a backend server --> so I wanted to use https://certbot.eff.org/ to generate certificates --> if I do so I get the following error: 

![Screenshot 2022-06-14 at 02 24 47](https://user-images.githubusercontent.com/43786652/173528192-b3fbd400-6b6a-46ad-9c7c-0f9ea7c7c0ac.png)

**Comment by patpatwithhat** [comment]
Is this just the API call giving you the error?
I would try it with postman if you share the parameters for header and body etc.
Is this an http or https website?

**Comment by michael-spengler** [comment]
> > > ### Regarding Point Number 1
> > > The newcomers (for which https://cultdao-ecosystem.eth.limo/ shall serve) might not have Ether in their browserwallet yet. This is the main reason why I hesitate to implement 1. --> ... so it looks like going for a centralized backend is reasonable in this context. --> exploring options to use https://certbot.eff.org/ in combination with an ens.domains & https://eth.limo/ based page provisioning.
> > 
> > 
> > I need to make API calls from https://cultdao-ecosystem.eth.limo/ to a backend server --> so I wanted to use https://certbot.eff.org/ to generate certificates --> if I do so I get the following error:
> > ![Screenshot 2022-06-14 at 02 24 47](https://user-images.githubusercontent.com/43786652/173528192-b3fbd400-6b6a-46ad-9c7c-0f9ea7c7c0ac.png)
> 
> Hi @michael-spengler, thanks for contacting us.
> 
> From what I can gather, it looks like you're wanting to spin up a backend API server and make requests to it from [cultdao-ecosystem.eth.limo/](https://cultdao-ecosystem.eth.limo/)? @eth-limo: yes, that's exactly correct.
> 
> Based on the screenshot above, it looks like certbot is attempting to reply to the ACME challenge using [cultdao-ecosystem.eth.limo/.well-known/...](https://cultdao-ecosystem.eth.limo/). This will not work however.
> 
> I suggest using your own domain name in conjunction with certbot and your backend API server. Something like this:
> 
> ```
> cultdao-ecosystem.eth.limo --HTTP Request--> api.yourdomain.com
> ```
@eth-limo: here I'm not quite sure in which command to use those parameters. 

I also just tried: 

```sh

sudo docker run -it --rm --name certbot \
    --volume "/tmp/etc-letsencrypt:/etc/letsencrypt" \
    --volume "/tmp/var-lib-letsencrypt:/var/lib/letsencrypt" \
    certbot/certbot certonly \
    --manual --manual-public-ip-logging-ok \
    --email michael@spengler.biz --agree-tos \
    --domain cultdao-ecosystem.eth.limo --rsa-key-size 2048 

```
with this I could generate the .well-known/acme-challenge/... file 

but then I got:
![Screenshot 2022-06-14 at 23 00 59](https://user-images.githubusercontent.com/43786652/173689330-73cb50cb-a9a2-45f7-aea0-953d8a1a5228.png)

> 
> Please join our discord server if you wish to discuss this further, happy to help answer any other questions. https://discord.gg/P45t678j2Y
